# Generated by Django 2.1.1 on 2019-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesto',
            name='cata',
            field=models.CharField(choices=[('sheji', '设计报告参考'), ('lunwen', '论文'), ('kejian', '课件'), ('qita', '其他')], default='qita', max_length=20, verbose_name='文件类别'),
        ),
    ]
