# Generated by Django 2.1.1 on 2019-03-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20190313_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesto',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filesto',
            name='cata',
            field=models.CharField(choices=[('kejian', '课件'), ('qita', '其他'), ('sheji', '设计报告参考'), ('lunwen', '论文')], default='kejian', max_length=20, verbose_name='文件类别'),
        ),
    ]
